# Generated by Django 4.2.14 on 2024-07-31 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0005_rename_emotion_after_tasks_changed_emotion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(blank=True, max_length=50, null=True)),
                ('focus_time', models.IntegerField(default=1500)),
                ('break_time', models.IntegerField(default=300)),
                ('cycle_number', models.IntegerField(default=1)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.tasks')),
            ],
        ),
    ]
