# Generated by Django 4.2.14 on 2024-07-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='task_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tasks',
            name='task_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
