# Generated by Django 4.2.14 on 2024-07-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tasks_task_description_tasks_task_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='sub_emotion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
