# Generated by Django 4.2.14 on 2024-07-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_tasks_sub_emotion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='task_emotion',
            new_name='emotion_after',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='sub_emotion',
        ),
        migrations.AddField(
            model_name='tasks',
            name='emotion_before',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
