# Generated by Django 4.2.14 on 2024-08-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_tasks_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='break_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tasks',
            name='focus_time',
            field=models.IntegerField(default=0),
        ),
    ]
