# Generated by Django 4.2.14 on 2024-08-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_tasks_break_time_tasks_focus_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='cycle_count',
            field=models.IntegerField(default=1),
        ),
    ]
